version: "3.6"

services:
  mongodb:
    image: mongo:4.4-bionic
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - db_data:/data/db

  api:
    depends_on:
      - mongodb
    ports:
      - ${API_PORT}:${API_PORT}
    restart: always
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    environment:
      PORT: ${API_PORT}
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_SECRET: ${APP_SECRET}
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    volumes:
      - .:/home/node/app

  web:
    depends_on:
      - api
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    restart: always
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    environment:
      PORT: ${WEB_PORT}
      NODE_ENV: ${NODE_ENV}
      API_URL: ${API_URL}
    volumes:
      - .:/home/node/app

volumes:
  db_data:
